NidTid.WebUI/Models/VehicleViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NidTid.WebUI.Models
{
    public class VehicleViewModel
    {
        public int Id { get; set; }
        public string RegNr { get; set; }
        public string Description { get; set; }
        public int CurrentMeter { get; set; }
        public string User { get; set; }
        public string Date { get; set; }

    }
}

NidTid.WebUI/Controllers/MeterPostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NidTid.Domain.Abstract;
using NidTid.Domain.Entities;
using NidTid.WebUI.Models;
using System.Web.Services;
using NidTid.WebUI.Security;


namespace NidTid.WebUI.Controllers
{
    public class MeterPostController : Controller
    {
        private IMeterPostRepository repository;
        private IVehicleRepository vehicleRepo;

        public MeterPostController(IMeterPostRepository repository, IVehicleRepository vehicleRepository)
        {
            this.repository = repository;
            this.vehicleRepo = vehicleRepository;
        }


        [HttpGet]
        [Authorize]
        public ActionResult NewMeterPost()
        {
            MeterPostViewModel meterpost = new MeterPostViewModel();
            meterpost.Vehicles = vehicleRepo.Vehicles;
            meterpost.MeterPost = new MeterPost();
            return PartialView(meterpost);
        }

        [HttpPost]
        [Authorize]
        public String SaveMeterPost(MeterPostViewModel meterModel)
        {
            MeterPost meterpost = meterModel.MeterPost;
            var identity = ((CustomPrincipal)HttpContext.User).CustomIdentity;
            meterpost.UserId = identity.UserId;
            //meterpost.CurrentMeter = Integer(meterModel.MeterPost.CurrentMeter);
            String message = "";
            if (ModelState.IsValid)
            {
                repository.SaveMeterPost(meterpost);
                message = "Rapporten har sparats!";
            }
            else
            {
                message = "Fel!";
            }
            return message;
        }

        [HttpPost]
        [Authorize]
        public string DeletePost(int id)
        {
            MeterPost post = repository.MeterPosts.FirstOrDefault(r => r.Id == id);
            repository.DeletePost(post);
            return "Posten är raderad";
        }

        [HttpGet]
        [Authorize]
        public ActionResult TableByVehicle(int vehicleId)
        {
            MeterPostListModel model = new MeterPostListModel();
            model.MeterPosts = repository.MeterPosts.Where(m => m.VehicleId == vehicleId).OrderByDescending(r => r.Id);
            return PartialView(model);
        }

    }
}

NidTid.WebUI/Controllers/VehicleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NidTid.Domain.Abstract;
using NidTid.Domain.Entities;
using NidTid.WebUI.Models;
using System.Web.Services;
using Newtonsoft.Json;

namespace NidTid.WebUI.Controllers
{
    public class VehicleController : Controller
    {
        private IVehicleRepository repository;
        private IMeterPostRepository meterpostRepository;

        public VehicleController(IVehicleRepository vehicleRepository, IMeterPostRepository meterpostRepo)
        {
            this.repository = vehicleRepository;
            this.meterpostRepository = meterpostRepo;
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Create() {
            Vehicle vehicle = new Vehicle();
            return PartialView(vehicle);
        }

        [HttpPost]
        public string Create(Vehicle vehicle)
        {
            string msg = "";
            if (ModelState.IsValid) {
                repository.SaveVehicle(vehicle);
                msg = "Fordonet är tillagt i databasen.";
            }
            else {
                msg = "Ett fel inträffade, försök igen.";
            }
            return msg;
        }

        [HttpGet]
        public ActionResult List()
        {
            VehicleListViewModel model = new VehicleListViewModel();
            model.Vehicles = repository.Vehicles;

            return PartialView(model);
        }

        [HttpGet]
        public ActionResult VehicleInfo(int id)
        {
            Vehicle vehicle = repository.Vehicles.FirstOrDefault(v => v.Id == id);
            VehicleViewModel model = new VehicleViewModel();
            model.Id = id;
            if (vehicle.MeterPost.Count() > 0) {
                MeterPost lastPost = vehicle.MeterPost.LastOrDefault(m => m.VehicleId == id);
                model.CurrentMeter = lastPost.CurrentMeter;
                model.Description = vehicle.Description;
                model.Date = lastPost.Date.ToShortDateString();
                model.User = lastPost.User.Name;
                model.RegNr = vehicle.RegNr;
            }
            else {
                model.CurrentMeter = 0;
                model.Description = vehicle.Description;
                model.Date = "-";
                model.User = "-";
                model.RegNr = vehicle.RegNr;
            }

            return PartialView(model);
        }

    }
}

NidTid.WebUI/Views/Vehicle/Create.cshtml
@model NidTid.Domain.Entities.Vehicle

<form id="vehicleForm" action="" method="post">
    <div class="modal-header">  
        <a class="close" data-dismiss="modal">×</a>  
        <h3>Nytt fordon</h3>  
    </div>
    <div id="vehicleModal" class="row-fluid">
        <div class="span10 offset2">
            @Html.LabelFor(model => model.RegNr)
            @Html.EditorFor(model => model.RegNr)
            @Html.LabelFor(model => model.Description)
            @Html.EditorFor(model => model.Description)
            @Html.EditorFor(model => model.Id)
        </div>
    </div>
    <div class="modal-footer">  
        <input type="button" id="createVehicle" class="btn btn-success" value="Spara"/>  
        <a href="#" class="btn" data-dismiss="modal">Avbryt</a>  
    </div>
</form>

NidTid.WebUI/Views/Vehicle/Index.cshtml
@model NidTid.WebUI.Models.VehicleListViewModel

@{
    ViewBag.Title = "Körjournal";
}

<div class="row-fluid">
    <div class="span12">
        <h3><img src="~/Content/Icons/folder.png" width="90" height="90">Körjournaler</h3>
    </div>
</div>

<div class="row-fluid">
    <div class="span4" id="newMeterPostDiv">
        @{
            Html.RenderAction("NewMeterPost", "MeterPost");
        }
    </div>
    <div class="span8" id="vehicleDiv">
        @{
            Html.RenderAction("List", "Vehicle");
        }
    </div>
</div>


<div id="meterPostModal" class="modal hide fade">
    <fieldset>
        <legend>Körjournal</legend>
        <div id="meterPostTable">

        </div>
    </fieldset>
</div>

NidTid.WebUI/Views/Vehicle/List.cshtml
@model NidTid.WebUI.Models.VehicleListViewModel

@{
  foreach (var v in Model.Vehicles) {
    <div class="row-fluid">
        @{
            Html.RenderAction("VehicleInfo", "Vehicle", new { id = v.Id});
        }
    </div>
  }  
}

NidTid.WebUI/Views/Vehicle/VehicleInfo.cshtml
@model NidTid.WebUI.Models.VehicleViewModel

<div class="span11 offset1">
    <fieldset>
        <legend>@Model.RegNr - @Model.Description</legend>
            <div class="row-fluid">
                Mätarställning: <b>@Model.CurrentMeter</b>
            </div>
            <div class="row-fluid">
                Senast använd <b>@Model.Date</b> av <b>@Model.User</b>
                <a data-vehicleId="@Model.Id" class="btn btn-info btn-small pull-right meterPostTable"><i class="icon-edit icon-white"></i>Visa körjournal</a>
            </div>
    </fieldset>
    <br/>
</div>