NidTid.WebUI/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NidTid.Domain.Abstract;
using NidTid.Domain.Entities;
using NidTid.WebUI.Models;
using System.Web.Services;


namespace NidTid.WebUI.Controllers {
    
    public class CustomerController : Controller {
        private ICustomerRepository repository;

        public CustomerController(ICustomerRepository customerRepository) {
            this.repository = customerRepository;
        }

        public ActionResult CustomerProjectSelect() {
            CustomersListViewModel model = new CustomersListViewModel {Customers = repository.Customers};
            return PartialView(model);
        }
        
        [HttpGet]
        [Authorize(Roles = "admin")]
        public ActionResult CustomerDetails(int? id) {
            Customer selectedCustomer = new Customer();
            if (id != null)
            {
                selectedCustomer = repository.Customers.FirstOrDefault(c => c.Id == id);
            }
            return View(selectedCustomer);
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public ActionResult CustomerDetails(Customer currentCustomer) {
            var currentId = 0;
            if (ModelState.IsValid) {
                currentId = repository.SaveCustomer(currentCustomer);
                TempData["message"] = "Kunduppgifterna har uppdaterats!";
            }
            else { 
                //FIXA FELMEDDELANDE
            }
            return RedirectToAction(actionName: "CustomerDetails", routeValues: new { id = currentId });
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public String DeleteCustomer(int id)
        {
            string msg = "";
            Customer customer = repository.Customers.FirstOrDefault(c => c.Id == id);
            if (customer.Project.Count() > 0)
            {
                msg = "Kan ej radera en kund med registrerade projekt!";
            }
            else {
                repository.DeleteCustomer(customer);
                msg = "Kunden har raderats ur databasen";
            }
            return msg;
        }


        [HttpGet]
        [Authorize(Roles = "admin")]
        public ActionResult Create() {
            Customer newCustomer = new Customer();
            return PartialView(newCustomer);
        }
        

        public ActionResult FilteredCustomers(string term)
        {
            var filteredCustomers = repository.Customers.Where(c => c.Name.StartsWith(term)).Select(c => new
            {
                label = c.Name,
                value = c.Id
            });
            return Json(filteredCustomers, JsonRequestBehavior.AllowGet);
        }

        
        public ActionResult FilteredProjects(int customerId) {
            Customer tempCustomer = repository.Customers.FirstOrDefault(c => c.Id == customerId);
            var filteredProjects = tempCustomer.Project.Where(proj => proj.Active == true).Select(p => new 
            {
                name = p.Name,
                id = p.Id
            });
            return Json(filteredProjects, JsonRequestBehavior.AllowGet);
        }

        public ActionResult FilteredProjectsAll(int customerId)
        {
            Customer tempCustomer = repository.Customers.FirstOrDefault(c => c.Id == customerId);
            var filteredProjects = tempCustomer.Project.Select(p => new
            {
                name = p.Name,
                id = p.Id
            });
            return Json(filteredProjects, JsonRequestBehavior.AllowGet);
        }


    }
}

NidTid.WebUI/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NidTid.Domain.Abstract;
using NidTid.Domain.Entities;
using NidTid.WebUI.Models;
using System.Web.Services;
using NidTid.WebUI.Security;

namespace NidTid.WebUI.Controllers
{
    public class ReportController : Controller
    {
        private IReportRepository repository;
        private ICustomerRepository customerRepo;
        private IUserRepository userRepo;

        public ReportController(IReportRepository reportRepository, ICustomerRepository customerRepository, IUserRepository userRepository)
        {
            this.repository = reportRepository;
            this.customerRepo = customerRepository;
            this.userRepo = userRepository;
        }

        [HttpGet]
        [Authorize]
        public ActionResult NewReport()
        {
            ReportViewModel report = new ReportViewModel();
            report.Report = new Report();
            report.Customers = customerRepo.ActiveCustomers;
            return View(report);
        }

        [HttpGet]
        [Authorize]
        public ActionResult EditReportModal(int reportId)
        {
            ReportViewModel report = new ReportViewModel();
            report.Report = repository.Reports.FirstOrDefault(r => r.Id == reportId);
            report.Customers = customerRepo.ActiveCustomers;
            return PartialView(report);
        }

        [HttpPost]
        [Authorize]
        public String SaveReport(ReportViewModel reportModel)
        {
            Report report = reportModel.Report;
            var identity = ((CustomPrincipal)HttpContext.User).CustomIdentity;
            report.UserId = identity.UserId;
            String message = "";
            if (ModelState.IsValid) {
                repository.SaveReport(report);
            }
            else {
                message = "Ett eller flera fält är fel ifyllda. Försök igen.";
            }
            return message;
        }

        [HttpPost]
        [Authorize]
        public void DeleteReport(int id)
        {
            Report report = repository.Reports.FirstOrDefault(r => r.Id == id);
            repository.DeleteReport(report);
        }

        [HttpGet]
        [Authorize]
        public ActionResult Spreadsheet()
        {
            SpreadsheetViewModel spreadsheet = new SpreadsheetViewModel();
            spreadsheet.Customers = customerRepo.Customers;
            spreadsheet.Users = userRepo.Users;
            return View(spreadsheet);
        }

        public ActionResult SpreadsheetResult(ReportQuery query)
        {
            var filteredReports = query.Filter(this.repository.Reports);
            SpreadsheetReportsModel model = new SpreadsheetReportsModel();
            model.Reports = filteredReports;
            model.DebTotal = (from r in filteredReports
                              select (decimal?)r.Deb).Sum() ?? 0;
            model.EjDebTotal = (from r in filteredReports
                              select (decimal?)r.EjDeb).Sum() ?? 0;
            model.TimeTotal = model.DebTotal + model.EjDebTotal;
            return PartialView(model);
        }

        public ActionResult List(ReportQuery query)
        {
            var filteredReports = query.Filter(this.repository.Reports);

            var k = filteredReports.ToList().Count;
            return PartialView(filteredReports);
        }

        public ActionResult UserSummary(int userId)
        {
            ReportSummaryViewModel reportSummary = new ReportSummaryViewModel(this.repository.Reports, userId);
            return PartialView(reportSummary);
        }


        
    }
}

NidTid.WebUI/Controllers/VehicleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NidTid.Domain.Abstract;
using NidTid.Domain.Entities;
using NidTid.WebUI.Models;
using System.Web.Services;
using Newtonsoft.Json;

namespace NidTid.WebUI.Controllers
{
    public class VehicleController : Controller
    {
        private IVehicleRepository repository;
        private IMeterPostRepository meterpostRepository;

        public VehicleController(IVehicleRepository vehicleRepository, IMeterPostRepository meterpostRepo)
        {
            this.repository = vehicleRepository;
            this.meterpostRepository = meterpostRepo;
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Create() {
            Vehicle vehicle = new Vehicle();
            return PartialView(vehicle);
        }

        [HttpPost]
        public string Create(Vehicle vehicle)
        {
            string msg = "";
            if (ModelState.IsValid) {
                repository.SaveVehicle(vehicle);
                msg = "Fordonet är tillagt i databasen.";
            }
            else {
                msg = "Ett fel inträffade, försök igen.";
            }
            return msg;
        }

        [HttpGet]
        public ActionResult List()
        {
            VehicleListViewModel model = new VehicleListViewModel();
            model.Vehicles = repository.Vehicles;

            return PartialView(model);
        }

        [HttpGet]
        public ActionResult VehicleInfo(int id)
        {
            Vehicle vehicle = repository.Vehicles.FirstOrDefault(v => v.Id == id);
            VehicleViewModel model = new VehicleViewModel();
            model.Id = id;
            if (vehicle.MeterPost.Count() > 0) {
                MeterPost lastPost = vehicle.MeterPost.LastOrDefault(m => m.VehicleId == id);
                model.CurrentMeter = lastPost.CurrentMeter;
                model.Description = vehicle.Description;
                model.Date = lastPost.Date.ToShortDateString();
                model.User = lastPost.User.Name;
                model.RegNr = vehicle.RegNr;
            }
            else {
                model.CurrentMeter = 0;
                model.Description = vehicle.Description;
                model.Date = "-";
                model.User = "-";
                model.RegNr = vehicle.RegNr;
            }

            return PartialView(model);
        }

    }
}

NidTid.WebUI/Views/Shared/_CustomerPartial.cshtml
@model NidTid.Domain.Entities.Customer 

 
<div class="span3">
    <a class="accordion-toggle" data-toggle="collapse" data-target="#editCustomerDiv" id="newCustomer" href="#customerTab"><img src="~/Content/Icons/users.png" width="30" height="30">Ny kund...</a>
    @if (Model.Name != null) {
    <fieldset>
        <legend>@Model.Name</legend>
        <div id="customerInfo">
            @Html.EditorFor(model => Model.Id)
            @Model.OrgNr <br />
            @Model.Adress <br />
            @Model.PostNr
            @Model.PostOrt <br />
            @Model.Phone1 <br />
            @Model.Email <br />
            <br />
        </div>
        <a class="btn btn-locked btn-info accordion-toggle" id="btnEditCustomer" data-toggle="collapse" data-target="#editCustomerDiv"><i class="icon-user icon-white"></i>Redigera kunduppgifter</a>
    </fieldset>
    }
</div>
<div class="span9">
    <div class="row-fluid collapse" id="editCustomerDiv">
        <div class="span12 well">
            <fieldset>
                <legend>Kunduppgifter</legend>
                <form id="customerForm" action="" method="post">
                    <div class="row-fluid">
                        <div class="span4">
                            @Html.LabelFor(model => model.Name)
                            @Html.EditorFor(model => model.Name)
                            @Html.LabelFor(model => model.OrgNr)
                            @Html.EditorFor(model => model.OrgNr)
                            @Html.LabelFor(model => model.Adress)
                            @Html.EditorFor(model => model.Adress)
                            @Html.LabelFor(model => model.PostNr)
                            @Html.EditorFor(model => model.PostNr)
                            @Html.LabelFor(model => model.PostOrt)
                            @Html.EditorFor(model => model.PostOrt)
                        </div>
                        <div class="span4">
                            @Html.LabelFor(model => model.Phone1)
                            @Html.EditorFor(model => model.Phone1)
                            @Html.LabelFor(model => model.Phone2)
                            @Html.EditorFor(model => model.Phone2)
                            @Html.LabelFor(model => model.Email)
                            @Html.EditorFor(model => model.Email)
                            @Html.LabelFor(model => model.Moms)
                            @Html.EditorFor(model => model.Moms)
                            @Html.EditorFor(model => model.Id)
                            <div class="row-fluid">
                                <br/>
                                <a class="btn btn-locked btn-success" id="saveCustomer"><i class="icon-ok icon-white"></i>Spara</a>
                            </div>
                        </div>
                    </div>
                </form>
            </fieldset>
        </div>
    </div>
</div>












    
    

NidTid.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" type="text/css" rel="stylesheet" />
    <link rel="stylesheet" href="@Url.Content("~/Content/themes/redmond/jquery-ui-1.10.3.custom.css")">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery-1.8.2.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.tablesorter.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery-ui-1.10.3.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/customers.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/bootbox.js")"></script>
    <link href="@Url.Content("~/Content/bootstrap/css/bootstrap.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/bootstrap/css/bootstrap-responsive.min.css")" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="container">
            <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="span3">
                    <a class="brand" href="@Url.Action("Index", "Home")"><img src="~/Content/Icons/nidlogo.png" class="span3" style="position:relative;top:10px"></a>
                </div>
                <div class="span9">
                    <div class="row-fluid">
                        <div class="span10">
                            <p class="pull-right">
                                @if (HttpContext.Current.User.Identity.IsAuthenticated)
                                {
                                    var identity = ((NidTid.WebUI.Security.CustomPrincipal)HttpContext.Current.User).CustomIdentity;
                                    @Html.Label(string.Format("Inloggad som: {0}, {1}", identity.FirstName, identity.UserRoleName))
                                }
                            </p>
                        </div>
                        <div class="span2">
                            <a href="@Url.Action("LogOut", "User")">Logga ut</a>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="span12">
                            @if (HttpContext.Current.User.Identity.IsAuthenticated)
                            {
                                <ul class="nav pull-right">
                                    <li><a href="@Url.Action("NewReport", "Report")"><img src="~/Content/Icons/time.png" width="38" height="38">Timrapport</a></li>
                                    <li class="divider-vertical"></li>
                                    <li><a href="@Url.Action("CustomerDetails", "Customer")"><img src="~/Content/Icons/users.png" width="38" height="38">Kunder</a><li>
                                    <li class="divider-vertical"></li>
                                    <li><a href="@Url.Action("Spreadsheet", "Report")"><img src="~/Content/Icons/spreadsheet.png" width="38" height="38">Sammanställningar</a></li>
                                    <li class="divider-vertical"></li>
                                    <li class="dropdown">  
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="~/Content/Icons/folder.png" width="38" height="38">Mer<b class="caret"></b></a>
                                        <ul class="dropdown-menu">
                                            <li><a href="@Url.Action("Index", "User")"><img src="~/Content/Icons/prof2.png" width="30" height="30">Personal</a></li>
                                            <li class="divider"></li> 
                                            <li><a href="@Url.Action("Index", "Vehicle")"><img src="~/Content/Icons/vehicle.png" width="30" height="30">Körjournal</a></li>
                                            <li class="divider"></li>
                                            <li><a href="#"><img src="~/Content/Icons/salary.png" width="30" height="30">Löner</a><li> 
                                        </ul>  
                                    </li>
                                </ul>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

 


    <div id="mainContent" class="container">
            @RenderBody()
    </div>



    

    <script src="@Url.Content("~/Scripts/bootstrap/bootstrap.min.js")" type="text/javascript"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

NidTid.WebUI/Views/Shared/_UserPartial.cshtml
@model NidTid.Domain.Entities.User

<div class="span3">
    @if (Model.Name != null) {
    <fieldset>
        <legend>@Model.Name</legend>
        <div id="customerInfo">
            @Html.EditorFor(model => Model.Id)
            @Model.PersNr <br />
            @Model.Role <br />
            @Model.Adress <br />
            @Model.PostNr
            @Model.PostOrt <br />
            @Model.Phone <br />
            @Model.Email <br />
            <br />
        </div>
        <a class="btn btn-locked btn-info accordion-toggle" id="btnEditUser" data-toggle="collapse" data-target="#editUserDiv"><i class="icon-user icon-white"></i>Redigera personuppgifter</a>
    </fieldset>
    }
</div>
<div class="span9">
    <div class="row-fluid collapse" id="editUserDiv">
        <div class="span12 well">
            <fieldset>
                <legend>Personuppgifter</legend>
                <form id="userForm" action="" method="post">
                    <div class="row-fluid">
                        <div class="span4">
                            @Html.LabelFor(model => model.Name)
                            @Html.EditorFor(model => model.Name)
                            @Html.LabelFor(model => model.PersNr)
                            @Html.EditorFor(model => model.PersNr)
                            @Html.LabelFor(model => model.Adress)
                            @Html.EditorFor(model => model.Adress)
                            @Html.LabelFor(model => model.PostNr)
                            @Html.EditorFor(model => model.PostNr)
                            @Html.LabelFor(model => model.PostOrt)
                            @Html.EditorFor(model => model.PostOrt)
                        </div>
                        <div class="span4">
                            @Html.LabelFor(model => model.Phone)
                            @Html.EditorFor(model => model.Phone)
                            @Html.LabelFor(model => model.Email)
                            @Html.EditorFor(model => model.Email)
                            @Html.LabelFor(model => model.Password)
                            @Html.EditorFor(model => model.Password)
                            @Html.LabelFor(model => model.Salary)
                            @Html.EditorFor(model => model.Salary)
                            @Html.LabelFor(model => model.Tax)
                            @Html.EditorFor(model => model.Tax)
                            @Html.EditorFor(model => model.Id)
                        </div>
                        <div class="span4">
                            @Html.LabelFor(model => model.Role)
                            <select name="Role">
                                <option value="@Model.Role">@Model.Role</option> 
                                <option value="Admin">Admin</option>
                                <option value="User">User</option>
                            </select>
                            <a class="btn btn-locked btn-success" id="saveUser"><i class="icon-ok icon-white"></i>Spara</a>
                        </div>
                    </div>
                </form>
            </fieldset>
        </div>
    </div>
</div>

NidTid.WebUI/Views/Shared/_newMeterPostPartial.cshtml
@model NidTid.WebUI.Models.MeterPostViewModel

<div class="span12 well">
    <form id="meterpostForm">
        <fieldset>
            <legend>Registrera ny post i körjournalen</legend>
            <div class="row-fluid">
                <div class="span4">
                    <div class="row-fluid">
                        Datum:
                    </div>
                    <div class="row-fluid">
                        RegNr
                    </div>
                </div>
                <div class="span4">
                    Notering:
                </div>
                <div class="span4">
                    <div class="row-fluid">
                        Mätarställning:
                    </div>
                    <div class="row-fluid">
                        Sparaknappen
                    </div>
                </div>
            </div>
        </fieldset>
    </form>
</div>